django_level_four/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING :

app_name ='basic_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),
]

django_level_four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import include, path
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'))
]

django_level_four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

django_level_four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello Ash','number':100}
    return render(request, 'basic_app/index.html',context_dict)

def other (request):
    return(render(request, 'basic_app/other.html'))

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')
































# from django.shortcuts import render

# # Create your views here.

# def index(request):
#     return render(request, 'basic_app/index.html')

# def other (request):
#     return(render(request, 'basic_app/other.html'))

# def relative(request):
#     return render(request, 'basic_app/relative_url_templates.html')

django_level_four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href=" {%url 'basic_app:other' %} ">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend!  -->
        {% endblock %}
    </div>
    
</body>
</html>

django_level_four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
  {% block body_block %}
    <h1>WELCOME TO INDEX!</h1>
    <!-- <h2>This is index.html page showing!</h2> -->
    <h1>{{ text|cut:'Ash' }}</h1>
    <h1>{{ number|add:"11" }}</h1>
  {% endblock %}

   

django_level_four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
  {% block body_block %}
    <h1>WELCOME TO OTHER!</h1>
    <h2>This is an example of template inheritance!</h2>
  {% endblock %}

   

django_level_four/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Welcome to this site!</title>
        
    </head>
    <body>
        <h1>Welcome to relative url templates!</h1>
        <a href="{% url 'basic_app:other'%}">THE OTHER PAGE</a>

        <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>

        <a href="{% url 'basic_app:index' %}">LINK TO INDEX</a>




    </body>
</html>