django_level_five/learning_users/basic_app/urls.py
from os import path
from django.conf.urls import url
from basic_app import views

# TEMPLATE URLS!
app_name = 'basic_app'

urlpatterns =[
    path('register',views.register,name='register')
]

django_level_five/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

django_level_five/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)


    # additional :

    portfolio_site = models.URLField(blank=True)


    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


    def __str__(self):
        return self.user.username   

django_level_five/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    passsword = forms.CharField(widget=forms.PasswordInput())


    class meta():
        model = User
        fields = ('username','email', 'password')


class UserProfileInfo(forms.ModelForm):

    
    class meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

django_level_five/learning_users/basic_app/views.py
from django.shortcuts import render

# Create your views here.

django_level_five/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Welcome to this site!</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                    <li><a class="navbar-link" href="{% 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %}

        </div>
    </body>
</html>

django_level_five/learning_users/templates/basic_app/index.html
{% extend "basic_app/base.html" % }
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five is Here!</h1>
</div>

{% endblock %}

django_level_five/learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block body_block%}
<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p}}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>
    
    {% endif %}
</div>